services:
  - type: web
    name: mkv-proxy
    env: node
    buildCommand: apt-get update && apt-get install -y ffmpeg && npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
